CREATE TABLE IF NOT EXISTS auth (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  account TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS todo (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  title TEXT NOT NULL,
  date TEXT NOT NULL,
  content TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS press (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  name TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS book (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  isbn TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  press_id INTEGER,
  FOREIGN KEY (press_id) REFERENCES press(id)
);
